### ISSUE TITLE
Return Spotify link in Spotify `extraAttrs`

### ISSUE THREAD

**Issue by ghostwriternr** [lttkgp/metadata-extractor#17]

**Comment by thescriptninja** [comment]
@ghostwriternr a `SongData` object has a `Track` object associated with it, which has the `provider_id` property. We can construct the Spotify link from this ID. Do we still need to return Spotify link in `extraAttrs`?

**Comment by ghostwriternr** [comment]
Ohh good catch @thescriptninja! Nope, we don't. Closing this issue.
