### ISSUE TITLE
Support YouTube Music links

### ISSUE THREAD

**Issue by thescriptninja** [lttkgp/metadata-extractor#27]
YouTube and YouTube music links share the same ID. Hence, we can support YT Music links.
The concerned files are:
https://github.com/lttkgp/metadata-extractor/blob/e88932c736d4f69d459a752b10e4098f79343273/music_metadata_extractor/resolver.py#L14
https://github.com/lttkgp/metadata-extractor/blob/e88932c736d4f69d459a752b10e4098f79343273/music_metadata_extractor/sources/youtube/core.py#L8

Metadata-extractor needs to recognize YT music links as valid links and extract the metadata after converting them to YT links.
For example, 
https://music.youtube.com/watch?v=J7p4bzqLvCw&list=RDAMVMJ7p4bzqLvCw would be treated as 
https://www.youtube.com/watch?v=J7p4bzqLvCw

**Comment by mukul-mehta** [comment]
Dang, you missed out on a Rickroll opportunity xD

**Comment by 2000yeshu** [comment]
Hey! I will take this up

**Comment by thescriptninja** [comment]
@mukul-mehta ahhh damn!! :joy: 
Also, note that this will entail a change to [this](https://github.com/lttkgp/C-3PO/blob/8ede13f7bb8f6fcf9656f35e24f809ef13570287/c3po/db/metadata.py#L16)
We will need to change and insert the incoming link as a YT link

**Comment by 2000yeshu** [comment]
Noted.

**Comment by mukul-mehta** [comment]
Fixed with #30
